name: Deploy Production
on:
  push:
    tags:
      - release/**

permissions:
  id-token: write
  contents: read

jobs:
  deployCdk :
    name: Deploy CDK Production
    environment: production
    runs-on:
      - self-hosted
      - codebuild-x64
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      uses: actions/setup-node@v3
      with:
        node-version: 18
    -
      name: Authenticate Via OIDC Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-1
        role-duration-seconds: 1800
        role-skip-session-tagging: true
        role-to-assume: arn:aws:iam::616010153635:role/GitHubActionRole
    -
      name: Assume CDK Deploy Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-1
        role-duration-seconds: 1800
        role-skip-session-tagging: true
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        role-to-assume: arn:aws:iam::240542634635:role/cdk-hnb659fds-deploy-role-240542634635-ap-southeast-1
        role-external-id: Pipeline
    -
      name: Deploy with CDK
      run: |-
        npm ci
        npm run build
        npx cdk deploy \
          --context RECORD_NAME=image \
          --context ZONE_NAME=popbela.com \
          --context ZONE_ID=Z04512592XKZQNHPIKVRT \
          --context S3_IMAGE_BUCKET_NAME=image-popbela-com \
          --all --require-approval never
